
cc_binary(
    name = "non_blocking_pipe",
    srcs = [
        "non_blocking_pipe.hpp",
        "test_pipe.cpp",
    ],
    deps = [
        # "//external:gtest",  # Assuming gtest is included as an external dependency
    ],
)
